package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "dampevillage")
public class Customer implements java.io.Serializable {

	private int customerId;
	private Privilage privilage;
	private String firstName;
	private String lastName;
	private String address1;
	private String address2;
	private String streetNumber;
	private String country;
	private String postalCode;
	private String email;
	private String state;
	private String contactMobile;
	private String userName;
	private String password;
	private String contactLand;
	private String title;
	private String nicPassportNo;
	private String passwordRecoverQuestion;
	private String passwordRecoverAnswer;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Customer() {
	}

	public Customer(int customerId) {
		this.customerId = customerId;
	}
	public Customer(int customerId, Privilage privilage, String firstName,
			String lastName, String address1, String address2,
			String streetNumber, String country, String postalCode,
			String email, String state, String contactMobile, String userName,
			String password, String contactLand, String title,
			String nicPassportNo, String passwordRecoverQuestion,
			String passwordRecoverAnswer, Set<Reservation> reservations) {
		this.customerId = customerId;
		this.privilage = privilage;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address1 = address1;
		this.address2 = address2;
		this.streetNumber = streetNumber;
		this.country = country;
		this.postalCode = postalCode;
		this.email = email;
		this.state = state;
		this.contactMobile = contactMobile;
		this.userName = userName;
		this.password = password;
		this.contactLand = contactLand;
		this.title = title;
		this.nicPassportNo = nicPassportNo;
		this.passwordRecoverQuestion = passwordRecoverQuestion;
		this.passwordRecoverAnswer = passwordRecoverAnswer;
		this.reservations = reservations;
	}

	@Id
	@Column(name = "customer_id", unique = true, nullable = false)
	@NotNull
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "privilage_id")
	public Privilage getPrivilage() {
		return this.privilage;
	}

	public void setPrivilage(Privilage privilage) {
		this.privilage = privilage;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "address1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "street_number")
	public String getStreetNumber() {
		return this.streetNumber;
	}

	public void setStreetNumber(String streetNumber) {
		this.streetNumber = streetNumber;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "postal_code")
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "contact_mobile")
	public String getContactMobile() {
		return this.contactMobile;
	}

	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "contact_land")
	public String getContactLand() {
		return this.contactLand;
	}

	public void setContactLand(String contactLand) {
		this.contactLand = contactLand;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "nic_passport_no")
	public String getNicPassportNo() {
		return this.nicPassportNo;
	}

	public void setNicPassportNo(String nicPassportNo) {
		this.nicPassportNo = nicPassportNo;
	}

	@Column(name = "password_recover_question")
	public String getPasswordRecoverQuestion() {
		return this.passwordRecoverQuestion;
	}

	public void setPasswordRecoverQuestion(String passwordRecoverQuestion) {
		this.passwordRecoverQuestion = passwordRecoverQuestion;
	}

	@Column(name = "password_recover_answer")
	public String getPasswordRecoverAnswer() {
		return this.passwordRecoverAnswer;
	}

	public void setPasswordRecoverAnswer(String passwordRecoverAnswer) {
		this.passwordRecoverAnswer = passwordRecoverAnswer;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
