package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * HotelProfile generated by hbm2java
 */
@Entity
@Table(name = "hotel_profile", catalog = "dampevillage")
public class HotelProfile implements java.io.Serializable {

	private int profileId;
	private String address1;
	private String address2;
	private String hotelDescription;
	private String direction;
	private String city;
	private String hotelName;
	private String country;
	private String contactNumber1;
	private String contactNumber2;
	private String postalCode;
	private String otherWebs;
	private String email;
	private String fax;

	public HotelProfile() {
	}

	public HotelProfile(int profileId) {
		this.profileId = profileId;
	}
	public HotelProfile(int profileId, String address1, String address2,
			String hotelDescription, String direction, String city,
			String hotelName, String country, String contactNumber1,
			String contactNumber2, String postalCode, String otherWebs,
			String email, String fax) {
		this.profileId = profileId;
		this.address1 = address1;
		this.address2 = address2;
		this.hotelDescription = hotelDescription;
		this.direction = direction;
		this.city = city;
		this.hotelName = hotelName;
		this.country = country;
		this.contactNumber1 = contactNumber1;
		this.contactNumber2 = contactNumber2;
		this.postalCode = postalCode;
		this.otherWebs = otherWebs;
		this.email = email;
		this.fax = fax;
	}

	@Id
	@Column(name = "profile_id", unique = true, nullable = false)
	@NotNull
	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	@Column(name = "address_1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address_2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "hotel_description")
	public String getHotelDescription() {
		return this.hotelDescription;
	}

	public void setHotelDescription(String hotelDescription) {
		this.hotelDescription = hotelDescription;
	}

	@Column(name = "direction")
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "hotel_name")
	public String getHotelName() {
		return this.hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "contact_number_1")
	public String getContactNumber1() {
		return this.contactNumber1;
	}

	public void setContactNumber1(String contactNumber1) {
		this.contactNumber1 = contactNumber1;
	}

	@Column(name = "contact_number_2")
	public String getContactNumber2() {
		return this.contactNumber2;
	}

	public void setContactNumber2(String contactNumber2) {
		this.contactNumber2 = contactNumber2;
	}

	@Column(name = "postal_code")
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "other_webs")
	public String getOtherWebs() {
		return this.otherWebs;
	}

	public void setOtherWebs(String otherWebs) {
		this.otherWebs = otherWebs;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fax")
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

}
