package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Privilage generated by hbm2java
 */
@Entity
@Table(name = "privilage", catalog = "dampevillage")
public class Privilage implements java.io.Serializable {

	private int privilageId;
	private String privilageName;
	private String description;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Privilage() {
	}

	public Privilage(int privilageId) {
		this.privilageId = privilageId;
	}
	public Privilage(int privilageId, String privilageName, String description,
			Set<Customer> customers) {
		this.privilageId = privilageId;
		this.privilageName = privilageName;
		this.description = description;
		this.customers = customers;
	}

	@Id
	@Column(name = "privilage_id", unique = true, nullable = false)
	@NotNull
	public int getPrivilageId() {
		return this.privilageId;
	}

	public void setPrivilageId(int privilageId) {
		this.privilageId = privilageId;
	}

	@Column(name = "privilage_name")
	public String getPrivilageName() {
		return this.privilageName;
	}

	public void setPrivilageName(String privilageName) {
		this.privilageName = privilageName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "privilage")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
