package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "dampevillage")
public class Reservation implements java.io.Serializable {

	private int reservationId;
	private Customer customer;
	private Payment payment;
	private AccomodationMode accomodationMode;
	private Date fromDate;
	private Date toDate;
	private String arrivalFrom;
	private String arriveFor;
	private String leaveAfter;
	private String airportPickup;
	private String nationality;
	private Integer noofRooms;
	private Integer adults;
	private Integer children;
	private String reservationStatus;
	private String roomCategory;
	private String roomType;
	private Integer roomCategoryId;
	private Integer roomTypeId;
	private Set<Roomreservation> roomreservations = new HashSet<Roomreservation>(
			0);

	public Reservation() {
	}

	public Reservation(int reservationId) {
		this.reservationId = reservationId;
	}
	public Reservation(int reservationId, Customer customer, Payment payment,
			AccomodationMode accomodationMode, Date fromDate, Date toDate,
			String arrivalFrom, String arriveFor, String leaveAfter,
			String airportPickup, String nationality, Integer noofRooms,
			Integer adults, Integer children, String reservationStatus,
			String roomCategory, String roomType, Integer roomCategoryId,
			Integer roomTypeId, Set<Roomreservation> roomreservations) {
		this.reservationId = reservationId;
		this.customer = customer;
		this.payment = payment;
		this.accomodationMode = accomodationMode;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.arrivalFrom = arrivalFrom;
		this.arriveFor = arriveFor;
		this.leaveAfter = leaveAfter;
		this.airportPickup = airportPickup;
		this.nationality = nationality;
		this.noofRooms = noofRooms;
		this.adults = adults;
		this.children = children;
		this.reservationStatus = reservationStatus;
		this.roomCategory = roomCategory;
		this.roomType = roomType;
		this.roomCategoryId = roomCategoryId;
		this.roomTypeId = roomTypeId;
		this.roomreservations = roomreservations;
	}

	@Id
	@Column(name = "reservation_id", unique = true, nullable = false)
	@NotNull
	public int getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(int reservationId) {
		this.reservationId = reservationId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_Id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_Id")
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accomodation_mode_id")
	public AccomodationMode getAccomodationMode() {
		return this.accomodationMode;
	}

	public void setAccomodationMode(AccomodationMode accomodationMode) {
		this.accomodationMode = accomodationMode;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "from_Date", length = 0)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "to_Date", length = 0)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "arrival_from")
	public String getArrivalFrom() {
		return this.arrivalFrom;
	}

	public void setArrivalFrom(String arrivalFrom) {
		this.arrivalFrom = arrivalFrom;
	}

	@Column(name = "arrive_for")
	public String getArriveFor() {
		return this.arriveFor;
	}

	public void setArriveFor(String arriveFor) {
		this.arriveFor = arriveFor;
	}

	@Column(name = "leave_after")
	public String getLeaveAfter() {
		return this.leaveAfter;
	}

	public void setLeaveAfter(String leaveAfter) {
		this.leaveAfter = leaveAfter;
	}

	@Column(name = "airport_pickup")
	public String getAirportPickup() {
		return this.airportPickup;
	}

	public void setAirportPickup(String airportPickup) {
		this.airportPickup = airportPickup;
	}

	@Column(name = "nationality")
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "noof_rooms")
	public Integer getNoofRooms() {
		return this.noofRooms;
	}

	public void setNoofRooms(Integer noofRooms) {
		this.noofRooms = noofRooms;
	}

	@Column(name = "adults")
	public Integer getAdults() {
		return this.adults;
	}

	public void setAdults(Integer adults) {
		this.adults = adults;
	}

	@Column(name = "children")
	public Integer getChildren() {
		return this.children;
	}

	public void setChildren(Integer children) {
		this.children = children;
	}

	@Column(name = "reservation_status")
	public String getReservationStatus() {
		return this.reservationStatus;
	}

	public void setReservationStatus(String reservationStatus) {
		this.reservationStatus = reservationStatus;
	}

	@Column(name = "room_category")
	public String getRoomCategory() {
		return this.roomCategory;
	}

	public void setRoomCategory(String roomCategory) {
		this.roomCategory = roomCategory;
	}

	@Column(name = "room_type")
	public String getRoomType() {
		return this.roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	@Column(name = "room_category_id")
	public Integer getRoomCategoryId() {
		return this.roomCategoryId;
	}

	public void setRoomCategoryId(Integer roomCategoryId) {
		this.roomCategoryId = roomCategoryId;
	}

	@Column(name = "room_type_id")
	public Integer getRoomTypeId() {
		return this.roomTypeId;
	}

	public void setRoomTypeId(Integer roomTypeId) {
		this.roomTypeId = roomTypeId;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "reservation")
	public Set<Roomreservation> getRoomreservations() {
		return this.roomreservations;
	}

	public void setRoomreservations(Set<Roomreservation> roomreservations) {
		this.roomreservations = roomreservations;
	}

}
