package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * RoomPool generated by hbm2java
 */
@Entity
@Table(name = "room_pool", catalog = "dampevillage")
public class RoomPool implements java.io.Serializable {

	private int roomPoolId;
	private RoomCategory roomCategory;
	private RoomType roomType;
	private Integer totalNoofRooms;
	private Integer availableRooms;

	public RoomPool() {
	}

	public RoomPool(int roomPoolId, RoomCategory roomCategory, RoomType roomType) {
		this.roomPoolId = roomPoolId;
		this.roomCategory = roomCategory;
		this.roomType = roomType;
	}
	public RoomPool(int roomPoolId, RoomCategory roomCategory,
			RoomType roomType, Integer totalNoofRooms, Integer availableRooms) {
		this.roomPoolId = roomPoolId;
		this.roomCategory = roomCategory;
		this.roomType = roomType;
		this.totalNoofRooms = totalNoofRooms;
		this.availableRooms = availableRooms;
	}

	@Id
	@Column(name = "room_pool_id", unique = true, nullable = false)
	@NotNull
	public int getRoomPoolId() {
		return this.roomPoolId;
	}

	public void setRoomPoolId(int roomPoolId) {
		this.roomPoolId = roomPoolId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_category_id", nullable = false)
	@NotNull
	public RoomCategory getRoomCategory() {
		return this.roomCategory;
	}

	public void setRoomCategory(RoomCategory roomCategory) {
		this.roomCategory = roomCategory;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_type_id", nullable = false)
	@NotNull
	public RoomType getRoomType() {
		return this.roomType;
	}

	public void setRoomType(RoomType roomType) {
		this.roomType = roomType;
	}

	@Column(name = "total_noof_rooms")
	public Integer getTotalNoofRooms() {
		return this.totalNoofRooms;
	}

	public void setTotalNoofRooms(Integer totalNoofRooms) {
		this.totalNoofRooms = totalNoofRooms;
	}

	@Column(name = "available_rooms")
	public Integer getAvailableRooms() {
		return this.availableRooms;
	}

	public void setAvailableRooms(Integer availableRooms) {
		this.availableRooms = availableRooms;
	}

}
