package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Roomreservation generated by hbm2java
 */
@Entity
@Table(name = "roomreservation", catalog = "dampevillage")
public class Roomreservation implements java.io.Serializable {

	private RoomreservationId id;
	private Room room;
	private Reservation reservation;

	public Roomreservation() {
	}

	public Roomreservation(RoomreservationId id, Room room,
			Reservation reservation) {
		this.id = id;
		this.room = room;
		this.reservation = reservation;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "reservationId", column = @Column(name = "reservation_Id", nullable = false)),
			@AttributeOverride(name = "roomId", column = @Column(name = "room_Id", nullable = false))})
	@NotNull
	public RoomreservationId getId() {
		return this.id;
	}

	public void setId(RoomreservationId id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_Id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reservation_Id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

}
