package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * RoomRates generated by hbm2java
 */
@Entity
@Table(name = "room_rates", catalog = "dampevillage")
public class RoomRates implements java.io.Serializable {

	private int roomRateId;
	private RoomCategory roomCategory;
	private RoomType roomType;
	private AccomodationMode accomodationMode;
	private Date validFrom;
	private Date validTo;
	private Long price;

	public RoomRates() {
	}

	public RoomRates(int roomRateId, RoomCategory roomCategory,
			RoomType roomType, AccomodationMode accomodationMode) {
		this.roomRateId = roomRateId;
		this.roomCategory = roomCategory;
		this.roomType = roomType;
		this.accomodationMode = accomodationMode;
	}
	public RoomRates(int roomRateId, RoomCategory roomCategory,
			RoomType roomType, AccomodationMode accomodationMode,
			Date validFrom, Date validTo, Long price) {
		this.roomRateId = roomRateId;
		this.roomCategory = roomCategory;
		this.roomType = roomType;
		this.accomodationMode = accomodationMode;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.price = price;
	}

	@Id
	@Column(name = "room_rate_id", unique = true, nullable = false)
	@NotNull
	public int getRoomRateId() {
		return this.roomRateId;
	}

	public void setRoomRateId(int roomRateId) {
		this.roomRateId = roomRateId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_category_id", nullable = false)
	@NotNull
	public RoomCategory getRoomCategory() {
		return this.roomCategory;
	}

	public void setRoomCategory(RoomCategory roomCategory) {
		this.roomCategory = roomCategory;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_type_id", nullable = false)
	@NotNull
	public RoomType getRoomType() {
		return this.roomType;
	}

	public void setRoomType(RoomType roomType) {
		this.roomType = roomType;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accomodation_mode_id", nullable = false)
	@NotNull
	public AccomodationMode getAccomodationMode() {
		return this.accomodationMode;
	}

	public void setAccomodationMode(AccomodationMode accomodationMode) {
		this.accomodationMode = accomodationMode;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from", length = 0)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to", length = 0)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Column(name = "price")
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

}
