package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * RoomCategory generated by hbm2java
 */
@Entity
@Table(name = "room_category", catalog = "dampevillage")
public class RoomCategory implements java.io.Serializable {

	private int roomCategoryId;
	private String roomCategotyType;
	private String description;
	private String imageName;
	private Set<RoomPool> roomPools = new HashSet<RoomPool>(0);
	private Set<Room> rooms = new HashSet<Room>(0);
	private Set<RoomRates> roomRateses = new HashSet<RoomRates>(0);

	public RoomCategory() {
	}

	public RoomCategory(int roomCategoryId) {
		this.roomCategoryId = roomCategoryId;
	}
	public RoomCategory(int roomCategoryId, String roomCategotyType,
			String description, String imageName, Set<RoomPool> roomPools,
			Set<Room> rooms, Set<RoomRates> roomRateses) {
		this.roomCategoryId = roomCategoryId;
		this.roomCategotyType = roomCategotyType;
		this.description = description;
		this.imageName = imageName;
		this.roomPools = roomPools;
		this.rooms = rooms;
		this.roomRateses = roomRateses;
	}

	@Id
	@Column(name = "room_category_id", unique = true, nullable = false)
	@NotNull
	public int getRoomCategoryId() {
		return this.roomCategoryId;
	}

	public void setRoomCategoryId(int roomCategoryId) {
		this.roomCategoryId = roomCategoryId;
	}

	@Column(name = "room_categoty_type")
	public String getRoomCategotyType() {
		return this.roomCategotyType;
	}

	public void setRoomCategotyType(String roomCategotyType) {
		this.roomCategotyType = roomCategotyType;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image_name")
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "roomCategory")
	public Set<RoomPool> getRoomPools() {
		return this.roomPools;
	}

	public void setRoomPools(Set<RoomPool> roomPools) {
		this.roomPools = roomPools;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "roomCategory")
	public Set<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "roomCategory")
	public Set<RoomRates> getRoomRateses() {
		return this.roomRateses;
	}

	public void setRoomRateses(Set<RoomRates> roomRateses) {
		this.roomRateses = roomRateses;
	}

}
