package com.seamaction.entity;
// Generated Nov 8, 2015 3:16:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * RoomreservationId generated by hbm2java
 */
@Embeddable
public class RoomreservationId implements java.io.Serializable {

	private int reservationId;
	private int roomId;

	public RoomreservationId() {
	}

	public RoomreservationId(int reservationId, int roomId) {
		this.reservationId = reservationId;
		this.roomId = roomId;
	}

	@Column(name = "reservation_Id", nullable = false)
	@NotNull
	public int getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(int reservationId) {
		this.reservationId = reservationId;
	}

	@Column(name = "room_Id", nullable = false)
	@NotNull
	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoomreservationId))
			return false;
		RoomreservationId castOther = (RoomreservationId) other;

		return (this.getReservationId() == castOther.getReservationId())
				&& (this.getRoomId() == castOther.getRoomId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReservationId();
		result = 37 * result + this.getRoomId();
		return result;
	}

}
